**Packages:**


* Directory of Python Scripts
* Each script = module
* Specify functions, methods, types
* Thousands of packages available: Numpy, Matplotlib, Scikit-learn, ...



To install a package, for instance numpy, in a Terminal use pip3 install numpy. Depending on the IDE you are using (Visual Code, Jupyter, Spyder, Anaconda, Pycharm,...), the process is different and Internet always helps ! 
I personally prefer professional Pycharm because we can use scripts and Jupyter notebooks together, virtual environments are part of it and there are many other nice functionalities. 

In [1]:
import numpy

array([1, 2, 3])
#NameError: name 'array' is not defined


NameError: name 'array' is not defined

In [2]:
numpy.array([1, 2, 3])
#array([1, 2, 3])
import numpy as np
print(np.array([1, 2, 3]))
#array([1, 2, 3])
from numpy import array
print(array([1, 2, 3]))
# array([1, 2, 3])

[1 2 3]
[1 2 3]


**Lists Recap**
* Collection of values
* Hold different types
* Change, add, remove
* Need for Data Science (Mathematical operations over collections, Speed, ...)

In [3]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
print(weight / height ** 2)
#TypeError: unsupported operand

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'



---

---



---





**Solution: NumPy**
* Numeric Python
* Alternative to Python List: NumPy Array
* Calculations over entire arrays
* Easy and Fast
* Installation: In the terminal: pip3 install numpy
Depending on the IDE you are using (Jupyter, Spyder, Anaconda, Pycharm,...), the process is different and Internet always helps ! 
I personally prefer professional Pycharm because we can use scripts and Jupyter notebooks together, virtual environments are part of it and there are many other nice functionalities. Moreover it is free for students and academic people.

In [4]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight / np_height ** 2
bmi # and now elementwise calculations work!


array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

**Different types: different behavior!**

In [5]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])
print(python_list + python_list)
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


**NumPy Subsetting:**

In [6]:
print(bmi)

print(bmi[1])

print(bmi > 23)

print(bmi[bmi > 23])



[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
20.97505668934241
[False False False  True False]
[24.7473475]


**2D NumPy Arrays**

In [ ]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
#ndarray = N-dimensional array
print(type(np_height))
print(type(np_weight))

In [ ]:
#2d example

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, 68.7], [1.73, 1.68, 1.71, 1.89, 1.79]])
print(np_2d)

print(np_2d.shape)

print(np_2d[0][2])
print(np_2d[0,2])

print(np_2d[:,1:3])
print(np_2d[1,:])

**Some useful numpy functions:**

In [ ]:
print(np.mean(np_2d[:,0]))
print(np.median(np_2d[:,0]))
print(np.corrcoef(np_2d[:,0], np_2d[:,1])) #correlation matrix
print(np.std(np_2d[:,0]))
print(np.sort(np_2d[:,0]))

**Generate data**

In [ ]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
print(height.shape) #the second 2 is applied by the round function
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
print(np_city.shape)



---



---



---



**Matplotlib**

In [ ]:
#A first example
import matplotlib.pyplot as plt
year = [1950, 1970, 1990, 2010]
pop = [2.519, 3.692, 5.263, 6.972]
plt.plot(year, pop)
plt.show()

In [ ]:
plt.scatter(year, pop)
plt.show()


**Histogram:** gives idea about distribution

In [ ]:
values = [0,0.6,1.4,1.6,2.2,2.5,2.6,3.2,3.5,3.9,4.2,6,1,5.5]
plt.hist(values, bins = 2) #The number of points which fall inside intervals
plt.show()

**Customization:**

In [ ]:
import matplotlib.pyplot as plt
year = [1950, 1970, 1990, 2010]
pop = [2.519, 3.692, 5.263, 6.972]
plt.plot(year, pop)
plt.xlabel('Year')
plt.ylabel('Population')
plt.title('World Population Projections')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
year = [1950, 1970, 1990, 2010]
pop = [2.519, 3.692, 5.263, 6.972]
plt.plot(year, pop)
plt.xlabel('Year')
plt.ylabel('Population')
plt.title('World Population Projections')
plt.yticks([0, 2, 4, 6, 8, 10]) #we change the scale
plt.show()



---



---



**Dictionnaries:**

A limitation of lists: 

In [ ]:
pop = [30.55, 2.77, 39.21]
countries = ["afghanistan", "albania", "algeria"]
ind_alb = countries.index("albania")
print(ind_alb)
print(pop[ind_alb])
#--------------> not intuitive. We want pop["albania"] but not possible


In [ ]:
#Dictionnary

world = {"afghanistan" : 30.55 , "albania" : 2.77 , "algeria" : 39.21}
print(world["albania"])
print(type(world)) #dict

"afghanistan", "albania", "algeria" are called keys of the dictionary.

In [ ]:
world["sealand"] = 0.000027
print(world)
world["sealand"] = 0.000028
print(world)
del(world["sealand"])
print(world)



---

---



---





**Pandas:**

![](https://drive.google.com/uc?export=view&id=1mxvJlPbPQPtEaAQq9IgroX2bmRu54jhv)

**DataFrame from Dictionary**

In [ ]:
dict = {
"country":["Brazil", "Russia", "India", "China", "South Africa"],
"capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
"area":[8.516, 17.10, 3.286, 9.597, 1.221],
"population":[200.4, 143.5, 1252, 1357, 52.98] }
print(type(dict))
print(dict)


In [ ]:
import pandas as pd
brics = pd.DataFrame(dict)
print(type(brics))
print(brics)

In [ ]:
#We want to index the dataframe with significant abbreviations

brics.index = ["BR", "RU", "IN", "CH", "SA"]
print(brics)

**DataFrame from CSV file**

CSV = comma-separated values

In [ ]:
from google.colab import files
uploaded = files.upload()
brics = pd.read_csv("data.csv")

In [ ]:
print(brics)

We see there are two indices columns at the begining.
Let us remove the first one (useless):

In [ ]:
brics = pd.read_csv("data.csv", index_col = 0)
print(brics)

**Index and Select Data:**

In [ ]:
brics["country"]

In [ ]:
type(brics["country"])
#1D labelled arrayS

We want brics["country"] to be a dataFrame. We slightly modify the code:

In [ ]:
brics[["country"]]
print(type(brics[["country"]]))

**Column Access [ ]**

In [ ]:
brics[["country", "capital"]]

<font color='green'>Look at how nice is the visualisation of dataframes !</font> 

**Row Access [ ]**

In [ ]:
brics[1:4]
#Remark that we count from 0 and here 1 is inclusive, whereas 4 is exclusive

**Row Access loc**

In [ ]:
print(brics.loc["RU"])
print(type(brics.loc["RU"]))

In [ ]:
#Let's do better with dataframes:

brics.loc[["RU"]]

#the type is a dataframe



In [ ]:
#with many

brics.loc[["RU", "IN", "CH"]]

In [ ]:
#We mix rows and columns
brics.loc[["RU", "IN", "CH"], ["country", "capital"]]

In [ ]:
#all rows and two selected columns
brics.loc[:, ["country", "capital"]]

**Row Access iloc**

In [ ]:
brics.iloc[[1]]

In [ ]:
brics.iloc[[1,2,3]]

In [ ]:
brics.iloc[[1,2,3], [0, 1]]

In [ ]:
brics.iloc[:, [0,1]]



---



---



---



# **Comparison Operators**

**Numeric comparisons**

In [ ]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi
print(bmi > 23)
bmi[bmi > 23]

**Other Comparisons**

In [ ]:
"carl" < "chris"
#True


In [ ]:
2!=3


# **Boolean Operators**

In [ ]:
True and True


In [ ]:
False and True

In [ ]:
True and False

In [ ]:
False and False

In [ ]:
x = 12
x > 5 and x < 15

In [ ]:
True or True

In [ ]:
False or True

In [ ]:
False or False

In [ ]:
y = 5
y < 7 or y > 13

In [ ]:
not True


In [ ]:
not False

In [ ]:
bmi # calculation of bmi left out
bmi > 21
bmi<22
bmi > 21 and bmi < 22
#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
bmi>21

In [ ]:
bmi<22

In [ ]:
np.logical_and(bmi > 21, bmi < 22)


In [ ]:
#Check np.logical_or
np.logical_or(bmi > 21, bmi < 22)

# **if, elif, else**

In [ ]:
z = 4
if z % 2 == 0 :
  print("z is even")

In [ ]:
z = 5
if z % 2 == 0 :
  print("z is even")
else:
  print("z is odd")

In [ ]:
z = 3
if z % 2 == 0 :
  print("z is divisible by 2")
elif z % 3 == 0 :
  print("z is divisible by 3")
else :
  print("z is neither divisible by 2 nor by 3")



---



---



# **Filtering Pandas DataFrame**

In [ ]:
brics

 <font color='blue'> Goal: Select countries with area over 8 million km2</font> 

3 steps
* Select the area column
* Do comparison on area column
* Use result to select countries

In [ ]:
brics["area"]

In [ ]:
brics["area"] > 8

In [ ]:
print(type(brics["area"] > 8))

In [ ]:
is_huge = brics["area"] > 8
is_huge

In [ ]:
brics[is_huge]

In [ ]:
#in one line code
brics[brics["area"] > 8]

**Boolean operators**

In [ ]:
brics[np.logical_and(brics["area"] > 8, brics["area"] < 10)]

**while loop**

In [ ]:
error = 50.0
while error > 1 :
  print(error)
  error = error/4

print(error)


**for loop**

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam :
  print(height)

**enumerate**

In [ ]:
for index, height in enumerate(fam) :
  print("index " + str(index) + ": " + str(height))

**loop over string**

In [ ]:
for c in "family" :
  print(c.capitalize())

**Loop Data Structures**

In [ ]:
#Here it does not work
world = { "afghanistan":30.55,
"albania":2.77,
"algeria":39.21 }
for key, value in world :
  print(key + " -- " + str(value))

In [ ]:
#Here we fix the error
for key, value in world.items() :
  print(key + " -- " + str(value))

In [ ]:
#loop on numpy arrays
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2

for val in bmi :
  print(val)

In [ ]:
#2d np arrays

import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in meas :
  print(val)

In [ ]:
#or better
for val in np.nditer(meas):
  print(val)


In [ ]:
print(brics)

In [ ]:
for val in brics :
  print(val) #only the columns names

In [ ]:
#we want all the information index by index

for lab, row in brics.iterrows() :
  print(lab)
  print(row)



**Selective print**

In [ ]:
for lab, row in brics.iterrows() :
  print(lab + ":" + row["capital"])

**Add column**

In [ ]:
for lab, row in brics.iterrows() :
  brics.loc[lab, "name_length"] = len(row ["country"])

brics

**apply function**

In [ ]:
brics

del(brics["name_length"])
brics

In [ ]:
brics["name_length"] = brics["country"].apply(len)
brics

**Random generators**

In [ ]:
np.random.rand()
np.random.seed(123)
print(np.random.rand())
np.random.seed(123)
print(np.random.rand())


In [ ]:
print(np.random.randint(0,2))
print(np.random.randint(0,10))

